spring:
  profiles:
    active: dev
  application:
    name: medo-payment-service
  datasource:
    url: ${PAYMENT_DATASOURCE_URL}
    username: ${PAYMENT_DATASOURCE_USERNAME}
    password: ${PAYMENT_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      validationQuery: select 1
channel:
  alipay:
    config:
      protocol: ${PROTOCOL:https}
      gateway-host: ${GATEWAY_HOST:openapi.alipaydev.com}
#      sign-type: RSA2
      app-id: ${APPID:2016091500516060}
      merchant-private-key: ${MERCHANT_PRIVATE_KEY:MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCpTLle7ZtZiG3LaQhou7kV9JTyU+1J/nDgyQLrrKOI82Y5U0owyZ/W6mU75rqO9ssGQNvOclUIsoZZmjsWHgRBcATwPzY6G0rPHfOZaKJZwgajcY/rrDNZ7b8mVEKnnUIjCVr8XzArDaXbO2vIREprhXsi6ZqFVb4stoeyJicDW8G9/27t3mCmQn9W53Ai45iyKZCkoNgNIsUQT8qyuXZ2SeNXB4aGD5uAmrP9zzyP2DeJUOL47tjoZxcyPdSYpQdy9e+Rn2IjGMT2RCjMAaX+2cKRVy8NK5Jwa4aFrDPaLKfRYkt9gcDlokO6JX0Gy0q0QJz/zy8ThcbHjJ6ZYikJAgMBAAECggEAe0qrqK0jOEW5p6va+uLS/GE842kpYnyQ2bKplNYJ1l9jb5Xvbq424D2c8c2qyRiDbA9pw+PRd18DpldCdm3vrXQVtJxkMlbT2Re34l2n9fPt/7NhG0ExuGkCjrhIPmaw1nEmuKndm0z6Hzkb2iGZjMoNjbRP2pBBybA4DA3q1W8VUqPf9LQ6oiUZIiRhNm0yN2+Tq9Jq+H4rMrasnOfAmk7jZWeaTjVZlltPNO3exMq55lBh/0tjTWSdkT5dkPOFNlBjpLqe1EInOPZiyAfUJHoUd6Js4OsGlRW+tXmBqReh2NwLMD76VRx6qs2eoINjhHo6/BA5NgpZfwxxu35hgQKBgQD8GYZE5e5TCRFcL/nlGaVU02eBueJsF3bL4Wcsu5PDtztiPc1AFa4lWf5273Gd+FQp4EN9jZMDekYFNwWdevDBv5zNDS0agGsJKIMiCLlPC1YvoO5EqDKSon1fm09oBgpXlPFUPJ9QQa/PK7wQndY9ZCJh3eGUB7cGsy0n4nnumQKBgQCr60JDF9crI9TFPvtioZ9TYmSle7IeQRIN5MaU7Jr4cvfLneb4jTqyuesCQwRJTwE5wDu7kzngnW7ulKsvU3cqoVKMWyS3OFcyOdkkxBK6JgCqFeoUWTnygcGylrT1/vZ1gF06BV8waG+xAVi9WCF7A9L9a4N4SXphLM42TOrD8QKBgQDTtqPaLLcvKMhZgTj+O8FrMXcVrQQH/tSXeB5rpMP9c139rSU4En0DhUZ8n63tGmWkHWDQihrSqtcu/fxLOroCHGcUlWIxhXNeZ5Vo+aaWSVECAsbXBeIi3y8nIYlYNOpujvj040xv3BpHg9UWp1cKi5OMWQhehvQgPk1H15zK0QKBgQCd1QttW0rQMUIaoBrcTzNdszxhbLF28xhnJvxlJt+TbsEt71ZoJAiaovMtjWc3AlBGu8RbDewZ2Y9Je7W5ajBCM/78GoUXrKLo2pEPHu9udIsxm5LegZggmp3AnnmeSifsch+kr9/XKlo4L9tPYcTDEhy3SehWG2c+JYtf8LerkQKBgQDheOMLp7AsS8BRRpOvOBJZDcZvZt6ymKaBjx2zdLFH139E2WP2bqHpcerwtLDcez3x+A1QH9vNZmdViP6+X+DIXhSuvwvKkd0JTsIhCzH9cY+shCLQv1ZcYkPzqUoEQLthr8uhIw02XcSUpOymDFnBXjOxJhp9dbAFrJTwN4t/ew==}
      alipay-public-key: ${ALIPAY_PUBLIC_KEY:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAorEIjxVTs6V8uYD96O2amZXaxJC7jOBZ1oKnYMz4yDg5vDXl9DRRh2me28IyuMzwPOxD8w/7JPbI1ZNTFtF0snxdkCVBHjx817xoAFEYUMUqEjYkNaEClalBeIXvNYUugvuqgRakEfDOVSysIlTu7hiVPznC2NQiv4DTsIU6d+pVE7jSVHzDFXQkxVYDOQd28Q21PvwkTCY4TYi7S+BYDFqHkKdW5cz/VlUQbqM2y+ZAsE8QlQLm8juxblb629plOGnYFA9k+har2j4lE15gxNbzuVHl3QpVhgxiSEGlaV6qUUY44I4AV69u4em1FGpEwtjTAZOK6IAq7iRvmuvbzQIDAQAB}
      notifyUrl: ${NOTIFY_URL:http://payment.luosheng.tech/paymentNotify}
      is-sand-box: ${IS_SAND_BOX:true}
logging:
  level:
    root: info

medo:
  payment:
    host-name: ${HOST_NAME:http://192.168.31.115:8080}
    cashier-host-name: ${HOST_NAME_CASHIER:http://192.168.31.115:4201}
    channel:
      deploy-remote: ${CHANNEL_DEPLOY_REMOTE:false}
    message:
      consumer:
        env:
          test: ${PAYMENT_MESSAGE_CCONSUMER_ENV_TEST:false}
  database:
    schema: ${MEDO_MESSEAGE_DATABASE:eventuate}
