version: '3.7'

services:
  medo-payment-service:
    container_name: payment-service
    image: medo/payment
    build: ./medo-payment/medo-payment-service
    ports:
      - "8081:8080"
    environment:
#      - JAVA_OPTS: -Xmx256m
      - SPRING_PROFILES_ACTIVE
      - PAYMENT_DATASOURCE_URL
      - PAYMENT_DATASOURCE_USERNAME
      - PAYMENT_DATASOURCE_PASSWORD
      - PROTOCOL
      - GATEWAY_HOST
      - APPID
      - MERCHANT_PRIVATE_KEY
      - ALIPAY_PUBLIC_KEY
      - NOTIFY_URL
      - IS_SAND_BOX
      - HOST_NAME
      - HOST_NAME_CASHIER
  payment-cashier-service:
    container_name: cashier-service
    image: medo/cashier
    ports:
      - "80:4201"
    build: ./payment-cashier
