server:
  port: 9104

spring:
  application:
    name: storage-service
  datasource:
    url: jdbc:mysql://localhost:3306/seata-demo?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    driver-class-name: org.mariadb.jdbc.Driver
  cloud:
    alibaba:
      seata:
        application-id: storage-service
        # seata 服务分组，要与服务端nacos-config.txt中service.vgroup_mapping的后缀对应，默认是${spring.application.name}-fescar-service-group
        tx-service-group: storage-service-group
